// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/study-app-design/Onyx.tsx": () => import("../components/mockups/study-app-design/Onyx.tsx"),
  "./components/mockups/study-app-design/Slate.tsx": () => import("../components/mockups/study-app-design/Slate.tsx"),
  "./components/mockups/study-app-design/Void.tsx": () => import("../components/mockups/study-app-design/Void.tsx")
};
